export const sections: Record<string, string[]> = {
    HEMATOLOGY: [
      "WBC",
      "RBC",
      "Hemoglobin",
      "Hematocrit",
      "Platelet Count",
      "MCV",
      "MCH",
      "MCHC",
      "RDW",
    ],
    "DIFFERENTIAL COUNT": [
      "Neutrophil",
      "Lymphocyte",
      "Monocyte",
      "Eosinophil",
      "Basophil",
    ],
    URINALYSIS: [
      "SpecificGravity",
      "pH",
      "Sugar (Urine)",
      "Protein (Urine)",
      "Ketone",
      "Blood",
      "Leukocytes",
      "Nitrite",
    ],
    "GENERAL CHEMISTRY": [
      "Glucose Fasting",
      "HbA1C",
      "Creatinine",
      "eGFR",
      "Sodium",
      "Potassium",
      "Chloride",
      "Alk Phosphatase",
      "ALT (SGPT)",
      "Uric Acid",
      "Cholesterol",
      "Triglycerides",
      "HDL Cholesterol",
      "LDL Cholesterol",
      "Chol:HDL Ratio",
      "NON-HDL Choleste",
      "Fasting",
      "TSH Ultra-sens",
      "Vitamin B12",
      "Ferritin",
      "VitD 25Hydroxy",
      "MicroalbuminRDMU",
      "Urine Creatinine",
      "MAL/Creat Ratio2",
    ],
  };
  