export const testDescriptions: Record<string, string> = {
    WBC: "White blood cells help fight infections.",
    RBC: "Red blood cells carry oxygen throughout your body.",
    Hemoglobin: "Measures the oxygen-carrying protein in your blood.",
    Hematocrit: "Percentage of blood made up of red blood cells.",
    "Platelet Count": "Platelets help your blood clot.",
    MCV: "Average size of your red blood cells.",
    MCH: "Average amount of hemoglobin per red blood cell.",
    MCHC: "Average concentration of hemoglobin in red blood cells.",
    RDW: "Variation in red blood cell size.",
    Neutrophil: "Type of white blood cell that fights infection.",
    Lymphocyte: "White blood cell important for immune function.",
    Monocyte: "White blood cell that helps remove dead cells.",
    Eosinophil: "White blood cell involved in allergic responses.",
    Basophil: "White blood cell involved in inflammation.",
    SpecificGravity: "Measures urine concentration.",
    pH: "Acidity or alkalinity of urine.",
    "Sugar (Urine)": "Detects glucose in urine.",
    "Protein (Urine)": "Detects protein in urine.",
    Ketone: "Measures ketones in urine.",
    Blood: "Detects blood in urine.",
    Leukocytes: "White blood cells in urine, may indicate infection.",
    Nitrite: "Indicates presence of bacteria in urine.",
    "Glucose Fasting": "Measures blood sugar after fasting.",
    HbA1C: "Average blood sugar over the past 2–3 months.",
    Creatinine: "Waste product from muscles, measures kidney function.",
    eGFR: "Estimates kidney function.",
    Sodium: "Important electrolyte in your blood.",
    Potassium: "Important for heart and muscle function.",
    Chloride: "Maintains fluid balance.",
    "Alk Phosphatase": "Enzyme related to liver and bone health.",
    "ALT (SGPT)": "Enzyme indicating liver function.",
    "Uric Acid": "Waste product from purines, high levels can cause gout.",
    Cholesterol: "Fat in your blood, risk factor for heart disease.",
    Triglycerides: "Type of fat in your blood.",
    "HDL Cholesterol": "Good cholesterol that helps remove bad cholesterol.",
    "LDL Cholesterol": "Bad cholesterol that can clog arteries.",
    "Chol:HDL Ratio": "Risk indicator for heart disease.",
    "NON-HDL Choleste": "All cholesterol minus HDL.",
    Fasting: "Duration patient fasted before test.",
    "TSH Ultra-sens": "Checks thyroid function.",
    "Vitamin B12": "Important for red blood cells and nerves.",
    Ferritin: "Stores iron in your body.",
    "VitD 25Hydroxy": "Measures vitamin D level for bone health.",
    "MicroalbuminRDMU": "Early indicator of kidney damage.",
    "Urine Creatinine": "Measures kidney function through urine.",
    "MAL/Creat Ratio1": "Ratio of microalbumin to creatinine in urine.",
    "MAL/Creat Ratio2": "Ratio of microalbumin to creatinine in urine (repeat test).",
    "CPK-Total": "Enzyme from muscles, high levels may indicate damage.",
    "Anti-HBs": "Antibody for Hepatitis B.",
    "Anti-HCV": "Antibody for Hepatitis C.",
    "Anti-HAV": "Antibody for Hepatitis A.",
  };